name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: npm
      - name: Node checks
        run: |
          npm ci
          npm test
          npm run lint

      - name: Install browsers
        env:
          DEBIAN_FRONTEND: noninteractive
          TZ: Etc/UTC
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y chromium-chromedriver

      - name: Run browser tests
        run: npm run browser-test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}